from __future__ import annotations

import os
import sys
from typing import Dict, Optional

import joblib
import numpy as np
import pandas as pd
import streamlit as st

# Ensure project root is on sys.path so we can reuse existing modules
ROOT_DIR = os.path.dirname(__file__)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from features.feature_engineering import add_fraud_features
from utils.data_loader import load_raw_data
from utils.preprocessing import TARGET_COL


MODELS_DIR = os.path.join(ROOT_DIR, "models", "saved_models")
EDA_PLOTS_DIR = os.path.join(ROOT_DIR, "eda", "plots")
EVAL_PLOTS_DIR = os.path.join(ROOT_DIR, "evaluation", "plots")


@st.cache_resource(show_spinner=False)
def load_metadata_and_models() -> tuple[Optional[dict], Dict[str, object]]:
    """Load saved metadata (preprocessor, splits) and trained models."""
    meta_path = os.path.join(MODELS_DIR, "metadata.joblib")
    meta: Optional[dict] = None
    if os.path.exists(meta_path):
        meta = joblib.load(meta_path)

    models: Dict[str, object] = {}
    for name in ["lightgbm", "xgboost", "random_forest", "logistic_regression"]:
        model_path = os.path.join(MODELS_DIR, f"{name}.joblib")
        if os.path.exists(model_path):
            models[name] = joblib.load(model_path)

    return meta, models


@st.cache_data(show_spinner=False)
def load_metrics_table() -> Optional[pd.DataFrame]:
    metrics_path = os.path.join(EVAL_PLOTS_DIR, "metrics_table.csv")
    if not os.path.exists(metrics_path):
        return None
    return pd.read_csv(metrics_path, index_col=0)


@st.cache_data(show_spinner=False)
def load_sample_data(nrows: int = 10000) -> Optional[pd.DataFrame]:
    """
    Load a small sample of the original dataset for demos / auto-fill.
    """
    dataset_path = os.path.join(ROOT_DIR, "dataset.csv")
    if not os.path.exists(dataset_path):
        return None
    try:
        df = load_raw_data(data_path=dataset_path, nrows=nrows)
        return df
    except Exception:
        return None


def render_eda_section() -> None:
    st.subheader("Exploratory Data Analysis (EDA)")
    st.markdown(
        "This section surfaces key EDA plots that were generated by `eda/eda_main.py`."
    )

    eda_files = [
        ("Fraud distribution", "fraud_distribution.png"),
        ("Amount distribution", "amount_histogram.png"),
        ("Log amount distribution", "log_amount_histogram.png"),
        ("Balance distributions", "balance_distributions.png"),
        ("Fraud vs transaction type", "fraud_vs_transaction_type.png"),
        ("Fraud vs amount", "fraud_vs_amount_boxplot.png"),
        ("Correlation heatmap", "correlation_heatmap.png"),
        ("Outliers (boxplots)", "outliers_boxplots.png"),
        ("KMeans elbow curve", "kmeans_elbow.png"),
        ("KMeans PCA clusters", "kmeans_pca_clusters.png"),
        ("Feature relationships (pairplot)", "feature_relationships_pairplot.png"),
    ]

    available_plots = [
        (title, os.path.join(EDA_PLOTS_DIR, fname))
        for title, fname in eda_files
        if os.path.exists(os.path.join(EDA_PLOTS_DIR, fname))
    ]

    if not available_plots:
        st.info(
            "No EDA plots found. Run `python eda/eda_main.py` first to generate them."
        )
        return

    for title, path in available_plots:
        st.markdown(f"**{title}**")
        st.image(path)


def render_evaluation_section() -> None:
    st.subheader("Model Evaluation")
    st.markdown(
        "View saved evaluation metrics and comparison plots generated by "
        "`evaluation/evaluate_models.py`."
    )

    metrics_df = load_metrics_table()
    if metrics_df is None:
        st.info(
            "Metrics table not found. Run `python evaluation/evaluate_models.py` "
            "after training models to populate evaluation results."
        )
    else:
        st.markdown("**Metrics table (test set)**")
        st.dataframe(metrics_df.style.format("{:.4f}"))

    # High-level comparison plots
    comparison_plots = [
        ("ROC curves", "roc_curves.png"),
        ("Precision–Recall curves", "precision_recall_curves.png"),
        ("Accuracy comparison", "model_comparison_accuracy.png"),
        ("Precision comparison", "model_comparison_precision.png"),
        ("Recall comparison", "model_comparison_recall.png"),
        ("F1-score comparison", "model_comparison_f1.png"),
        ("ROC AUC comparison", "model_comparison_roc_auc.png"),
        ("PR AUC comparison", "model_comparison_pr_auc.png"),
    ]

    available_eval_plots = [
        (title, os.path.join(EVAL_PLOTS_DIR, fname))
        for title, fname in comparison_plots
        if os.path.exists(os.path.join(EVAL_PLOTS_DIR, fname))
    ]

    if available_eval_plots:
        st.markdown("**Global evaluation plots**")
        for title, path in available_eval_plots:
            st.markdown(f"**{title}**")
            st.image(path)

    # Per-model confusion matrices
    st.markdown("**Confusion matrices (per model)**")
    for model_name in ["logistic_regression", "random_forest", "xgboost", "lightgbm"]:
        cm_path = os.path.join(EVAL_PLOTS_DIR, model_name, "confusion_matrix.png")
        if os.path.exists(cm_path):
            st.markdown(f"**{model_name}**")
            st.image(cm_path, use_column_width=True)

    # SHAP explainability plots (if available)
    shap_dir = os.path.join(EVAL_PLOTS_DIR, "shap")
    if os.path.isdir(shap_dir):
        shap_files = [
            f for f in os.listdir(shap_dir) if f.endswith(".png")
        ]
        if shap_files:
            st.markdown("**SHAP explainability plots**")
            for fname in shap_files:
                st.markdown(f"`{fname}`")
                st.image(os.path.join(shap_dir, fname))


def prepare_inference_features(
    df_raw: pd.DataFrame, meta: Optional[dict]
) -> tuple[np.ndarray, Optional[np.ndarray], pd.DataFrame]:
    """
    Apply feature engineering and preprocessing to a raw DataFrame for inference.

    Returns:
        X_processed: transformed features ready for model.predict / predict_proba
        y_true: optional ground-truth labels if present
        df_with_features: engineered feature DataFrame aligned with training schema
    """
    if meta is None:
        raise RuntimeError("Model metadata not found. Train models before prediction.")

    preprocessor = meta.get("preprocessor")
    if preprocessor is None:
        raise RuntimeError("Preprocessor not found in metadata.")

    df = df_raw.copy()

    # Optional ground truth if user provided labels
    y_true: Optional[np.ndarray] = None
    if TARGET_COL in df.columns:
        y_true = df[TARGET_COL].values.astype(int)

    # Apply the same feature engineering used during training
    df = add_fraud_features(df)

    # Drop target column for preprocessing, if present
    if TARGET_COL in df.columns:
        df_features = df.drop(columns=[TARGET_COL])
    else:
        df_features = df

    # Use the fitted preprocessor from training
    X_processed = preprocessor.transform(df_features)
    return X_processed, y_true, df_features


def render_prediction_section(meta: Optional[dict], models: Dict[str, object]) -> None:
    st.subheader("Fraud Prediction")
    st.markdown(
        "Run fraud risk predictions using the trained models, either on a batch of "
        "transactions (CSV) or on a single manually-edited transaction."
    )

    if not models:
        st.warning(
            "No trained models were found in `models/saved_models/`. "
            "Run `python models/train_models.py` first."
        )
        return

    default_model_order = ["lightgbm", "xgboost", "random_forest", "logistic_regression"]
    available_model_names = [m for m in default_model_order if m in models]
    if not available_model_names:
        available_model_names = list(models.keys())

    selected_model_name = st.selectbox(
        "Select model for prediction",
        options=available_model_names,
        index=0,
    )

    threshold = st.slider(
        "Fraud probability threshold",
        min_value=0.05,
        max_value=0.95,
        value=0.5,
        step=0.05,
    )

    tab_batch, tab_single = st.tabs(["Batch CSV", "Single entry"])

    # --- Batch CSV tab ---
    with tab_batch:
        col_upload, col_sample = st.columns(2)
        with col_upload:
            uploaded_file = st.file_uploader(
                "Upload CSV with the same schema as `dataset.csv` (excluding identifiers).",
                type=["csv"],
                key="batch_csv_uploader",
            )
        with col_sample:
            use_sample = st.button("Load sample from dataset.csv")

        df_raw: Optional[pd.DataFrame] = None

        if use_sample:
            sample_df = load_sample_data(nrows=5000)
            if sample_df is None:
                st.error("Could not load sample from `dataset.csv`. Make sure the file exists.")
                return
            df_raw = sample_df
            st.success("Loaded a sample of 5,000 rows from `dataset.csv`.")
        elif uploaded_file is not None:
            try:
                df_raw = pd.read_csv(uploaded_file)
            except Exception as exc:  # pragma: no cover - defensive
                st.error(f"Failed to read CSV: {exc}")
                return

        if df_raw is None:
            st.info(
                "Upload a CSV file or click 'Load sample from dataset.csv' to run batch predictions."
            )
        else:
            st.markdown("**Preview of batch data**")
            st.dataframe(df_raw.head())

            if st.button("Run batch prediction"):
                try:
                    X_processed, y_true, df_features = prepare_inference_features(df_raw, meta)
                except Exception as exc:  # pragma: no cover - defensive
                    st.error(f"Error while preparing features for prediction: {exc}")
                    return

                model = models[selected_model_name]
                if hasattr(model, "predict_proba"):
                    y_proba = model.predict_proba(X_processed)[:, 1]
                elif hasattr(model, "decision_function"):
                    scores = model.decision_function(X_processed)
                    scores = (scores - scores.min()) / (scores.max() - scores.min() + 1e-8)
                    y_proba = scores
                else:
                    y_pred_raw = model.predict(X_processed)
                    y_proba = y_pred_raw.astype(float)

                y_pred = (y_proba >= threshold).astype(int)

                result_df = df_features.copy()
                result_df["fraud_probability"] = y_proba
                result_df["fraud_prediction"] = y_pred

                if y_true is not None and len(y_true) == len(result_df):
                    result_df[TARGET_COL] = y_true

                st.markdown("**Batch prediction results (top 100 rows)**")
                st.dataframe(result_df.head(100))

                st.markdown("**Summary**")
                st.write(f"Total records scored: {len(result_df)}")
                st.write(
                    f"Predicted fraud cases (probability ≥ {threshold:.2f}): "
                    f"{int(result_df['fraud_prediction'].sum())}"
                )

    # --- Single entry tab ---
    with tab_single:
        st.markdown(
            "Use the form below to enter a single transaction. "
            "You can auto-fill the fields from a random row in `dataset.csv` and then edit."
        )

        sample_df = load_sample_data()

        if "single_entry_values" not in st.session_state:
            if sample_df is not None and not sample_df.empty:
                # Use the first row as an initial template
                st.session_state.single_entry_values = sample_df.iloc[0].to_dict()
            else:
                st.session_state.single_entry_values = {}

        if st.button("Auto-fill from dataset.csv"):
            if sample_df is None or sample_df.empty:
                st.error("Could not load sample from `dataset.csv` for auto-fill.")
            else:
                # Pick a fresh random row on each click
                random_row = sample_df.sample(1).iloc[0]
                st.session_state.single_entry_values = random_row.to_dict()
                st.success("Auto-filled fields from a random row in `dataset.csv`.")

        values = st.session_state.single_entry_values

        if sample_df is None or sample_df.empty:
            st.info(
                "For best results, place `dataset.csv` in the project root so the form can "
                "use real column names and value ranges."
            )
            return

        # Build form fields dynamically from sample_df schema
        with st.form("single_entry_form"):
            form_inputs: Dict[str, object] = {}

            for col in sample_df.columns:
                # Ground-truth label is optional in single-entry mode
                if col == TARGET_COL:
                    current = values.get(col, "")
                    label_option = st.selectbox(
                        f"{col} (optional ground truth)",
                        options=["(none)", 0, 1],
                        index=0 if current == "" else (2 if current == 1 else 1),
                    )
                    form_inputs[col] = None if label_option == "(none)" else int(label_option)
                    continue

                dtype = sample_df[col].dtype
                # Fallback to first-row value if nothing in session state yet
                fallback_value = sample_df[col].iloc[0] if sample_df is not None and not sample_df.empty else None
                current = values.get(col, fallback_value)

                if np.issubdtype(dtype, np.number):
                    default_val = float(current) if current is not None else 0.0
                    form_inputs[col] = st.number_input(
                        col,
                        value=default_val,
                    )
                else:
                    # For transaction type (and other categoricals), use known unique values if available
                    unique_vals = None
                    try:
                        unique_vals = sorted(
                            v for v in sample_df[col].dropna().unique().tolist() if v != ""
                        )
                    except Exception:
                        unique_vals = None

                    if unique_vals:
                        default_index = 0
                        if current in unique_vals:
                            default_index = unique_vals.index(current)
                        form_inputs[col] = st.selectbox(
                            col,
                            options=unique_vals,
                            index=default_index,
                        )
                    else:
                        form_inputs[col] = st.text_input(
                            col,
                            value=str(current) if current is not None else "",
                        )

            submitted = st.form_submit_button("Run single-entry prediction")

        if submitted:
            st.session_state.single_entry_values = form_inputs

            df_single = pd.DataFrame([form_inputs])
            try:
                X_processed, y_true, df_features = prepare_inference_features(df_single, meta)
            except Exception as exc:  # pragma: no cover - defensive
                st.error(f"Error while preparing features for prediction: {exc}")
                return

            model = models[selected_model_name]
            if hasattr(model, "predict_proba"):
                y_proba = model.predict_proba(X_processed)[:, 1]
            elif hasattr(model, "decision_function"):
                scores = model.decision_function(X_processed)
                scores = (scores - scores.min()) / (scores.max() - scores.min() + 1e-8)
                y_proba = scores
            else:
                y_pred_raw = model.predict(X_processed)
                y_proba = y_pred_raw.astype(float)

            prob = float(y_proba[0])
            pred = int(prob >= threshold)

            st.markdown("**Single-entry prediction**")
            st.write(f"Fraud probability: **{prob:.4f}**")
            st.write(f"Fraud prediction (threshold {threshold:.2f}): **{pred}**")

            if y_true is not None and len(y_true) == 1 and y_true[0] is not None:
                st.write(f"Provided ground truth `isFraud`: **{int(y_true[0])}**")


def main() -> None:
    st.set_page_config(
        page_title="Insurance Fraud Detection Dashboard",
        layout="wide",
    )
    st.title("Insurance Fraud Detection – Interactive Dashboard")
    st.markdown(
        "Use this Streamlit app to explore EDA results, inspect model evaluation, "
        "and run fraud predictions on new transaction data."
    )

    meta, models = load_metadata_and_models()

    section = st.sidebar.radio(
        "Navigation",
        options=["EDA", "Evaluation", "Predict"],
        index=0,
    )

    if section == "EDA":
        render_eda_section()
    elif section == "Evaluation":
        render_evaluation_section()
    else:
        render_prediction_section(meta, models)


if __name__ == "__main__":
    main()

